version: '3.3'

services:
   db_presta:
     build: ./docker/db/
     ports:
      - '3307:3306'
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: prestashop_db
       MYSQL_USER: ps
       MYSQL_PASSWORD: ps

   prestashop1:
    build: ./docker/presta/
    restart: always
    depends_on:
      - db_presta
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ../log:/var/log/apache2/
   prestashop2:
    build: ./docker/presta/
    restart: always
    depends_on:
      - db_presta
    ports:
      - '8282:80'
   nginx:
    build: ./docker/nginx
    restart: always
    depends_on:
      - prestashop1
      - prestashop2
    ports:
      - "81:80" 
      
   phpmyadmin:
     depends_on:
       - db_presta
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - '8181:80'
     environment:
       PMA_HOST: db_presta
       
       